# Generated by Django 4.0.6 on 2022-07-16 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cafepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cafe',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.addresslevelthree'),
        ),
        migrations.AddField(
            model_name='addressleveltwo',
            name='super_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.addresslevelone'),
        ),
        migrations.AddField(
            model_name='addresslevelthree',
            name='super_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.addressleveltwo'),
        ),
    ]
