# Generated by Django 4.0.6 on 2022-07-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafecomplexity',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexities', to='cafes.cafe'),
        ),
    ]
